In [1]:
import numpy as np
arr1 = np.array([1, 2, 3, 6]) #矩阵运算
arr2 = np.arange(4)
arr_sub_1 = arr1 - arr2 # 矩阵减法，加法同理
arr_sub_2 = arr1 + arr2
print(arr1)
print(arr2)
print(arr_sub_1)
print(arr_sub_2)

[1 2 3 6]
[0 1 2 3]
[1 1 1 3]
[1 3 5 9]


In [2]:
arr_multi = arr1 ** 3  # 求每个元素的⽴⽅，在python中幂运算⽤**来表示
print(arr_multi)

[  1   8  27 216]


In [3]:
arr_multi = arr1 * arr2 # 元素逐个相乘
print(arr_multi)

[ 0  2  6 18]


In [4]:
arr_multi = np.dot(arr1, arr2.reshape((4, 1)))  # 点乘， 点对点相乘在相加， 列数与行数相同
print(arr_multi)

[26]


In [5]:
arr_multi = np.dot(arr1.reshape((4, 1)),  arr2.reshape((1, 4)))  # x乘， 对应元素相乘， 维度必须状相同， 乘出来的结果
print(arr_multi)

[[ 0  1  2  3]
 [ 0  2  4  6]
 [ 0  3  6  9]
 [ 0  6 12 18]]


In [6]:
arr_multi = arr1.dot(arr2.reshape((4, 1))) # 也可以使⽤矩阵名.doc(矩阵名)
print(arr_multi)

[26]


In [7]:
arr_sin = np.sin(arr1) # 三⻆运算：np.sin()/np.cos()/np.tan()
arr_cos = np.cos(arr1)
arr_tan = np.tan(arr1)
print(arr_sin)
print(arr_cos)
print(arr_tan)

[ 0.84147098  0.90929743  0.14112001 -0.2794155 ]
[ 0.54030231 -0.41614684 -0.9899925   0.96017029]
[ 1.55740772 -2.18503986 -0.14254654 -0.29100619]


In [8]:
print(arr1<3)  # 查看arr1矩阵中哪些元素⼩于3，返回[ True True False False

[ True  True False False]


In [9]:
arr1 = np.array([[1, 2, 3], # 矩阵求和，求矩阵最⼤最⼩值
               [4, 5, 6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [10]:
print(np.sum(arr1)) #矩阵求和

21


In [11]:
print(np.sum(arr1, axis = 0))  # 矩阵每列求和

[5 7 9]


In [12]:
print(np.sum(arr1, axis = 1).reshape(2, 1))  # 矩阵每⾏求和

[[ 6]
 [15]]


In [15]:
print(np.min(arr1))  # 求矩阵最⼩值

1


In [16]:
print(np.min(arr1, axis = 0)) #求矩阵没列最小值

[1 2 3]


In [17]:
print(np.min(arr1, axis = 1)) #求矩阵每行最小的值

[1 4]


In [18]:
print(np.max(arr1)) #求矩阵最大值

6


In [19]:
print(np.max(arr1, axis = 0)) #求矩阵每列的最大值

[4 5 6]


In [20]:
print(np.max(arr1, axis = 1)) #求矩阵每行最大值

[3 6]


In [22]:
print(np.mean(arr1))  # 输出矩阵平均值，也可以⽤arr1.mean()
print(arr1.mean())

3.5
3.5


In [26]:
print(np.median(arr1)) #求矩阵的中位数

3.5


In [30]:
arr1 = np.arange(2, 14).reshape(3, 4)
print(arr1)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [31]:
print(np.argmin(arr1)) #输出矩阵最小值的位置

0


In [32]:
print(np.argmax(arr1)) #输出矩阵最大值的位置

11


In [33]:
print(np.cumsum(arr1))  # 输出前⼀个数的和，前两个数的和，等等

[ 2  5  9 14 20 27 35 44 54 65 77 90]


In [34]:
print(np.diff(arr1))  # 输出相邻两个数的差值

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [39]:
arr_zeros = np.zeros((3, 4)) #输出矩阵⾮零元素位置，返回多个⾏向量，第i个⾏向量表示第i个维度
print(np.nonzero(arr_zeros))

(array([], dtype=int64), array([], dtype=int64))


In [40]:
print(np.nonzero(arr1))

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


In [41]:
print(np.sort(arr1))  # 矩阵逐⾏排序


[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [44]:
print(np.transpose(arr1))  # 矩阵转置，也可以⽤arr1.T
print(arr1.transpose())

[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]


In [47]:
print(np.clip(arr1, 5, 9))  #将矩阵中⼩于5的数置5，⼤于9的数置9

[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]
