In [3]:
import numpy as np

In [4]:
arr1 = np.array([1, 2, 3, 6])
arr2 = np.arange(2, 8).reshape(2, 3)
print(arr1)
print(arr1[0])  # 索引从0开始计数
print(arr2)
print(arr2[0][2]) # arr[⾏][列]，也可以⽤arr[⾏,列]
print(arr2[0:])  # ⽤:来代表所有元素的意思
print(arr2[0, 0:3])  # 表示输出第0⾏，从第0列到第2列所有元素

[1 2 3 6]
1
[[2 3 4]
 [5 6 7]]
4
[[2 3 4]
 [5 6 7]]
[2 3 4]


In [5]:
# 通过for循环每次输出矩阵的⼀⾏
for row in arr2:
    print(row)

[2 3 4]
[5 6 7]


In [8]:
arr2_T = arr2.T  #如果要每次输出矩阵的⼀列，就先将矩阵转置
print(arr2_T)
for row in arr2_T:
    print(row)

[[2 5]
 [3 6]
 [4 7]]
[2 5]
[3 6]
[4 7]


In [11]:
arr2_flat = arr2.flatten() # 将矩阵压成⼀⾏逐个输出元素
print(arr2_flat)
for i in arr2.flat:
    print(i)

[2 3 4 5 6 7]
2
3
4
5
6
7
