In [18]:
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
type(a)

numpy.ndarray

In [20]:
a.shape

(12,)

In [21]:
a.shape = 3, 4

In [22]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
a[2, 1]

9

In [24]:
a[:, 1]

array([1, 5, 9])

In [25]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [27]:
floats = np.loadtxt('floats-10M-lines.txt')
floats[-3:]

FileNotFoundError: [Errno 2] No such file or directory: 'floats-10M-lines.txt'