In [1]:
import numpy as np
a=np.array([1,2,3,4,5],dtype=np.int64)
print(a)
print(type([1,2,3,4,5]))
print(type(a))
print(a.dtype)


[1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>
int64


In [9]:
a = np.linspace(1, 10, 10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [14]:
a = np.arange(2, 200, 2)
print(a)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198]


In [17]:
a = np.logspace(0, 20, 5)
print(a)

[1.e+00 1.e+05 1.e+10 1.e+15 1.e+20]


In [43]:
def funcA (i):
    return (i + 1)*2
a = np.fromfunction(funcA,(5,))
print(a)

[ 2.  4.  6.  8. 10.]


In [47]:
a = np.array([[1, 2, 3],
             [4, 5, 6]
             ])
print(a)
print(a.shape)
print(a.shape[0]*a.shape[1])

[[1 2 3]
 [4 5 6]]
(2, 3)
6


In [48]:
b = np.array([[1, 2, 3],
             [4, 5, 6]
             ])
b = b.reshape(3, 2)
print(b)


[[1 2]
 [3 4]
 [5 6]]


In [77]:
a = np.arange(1, 10, 1)
b = a
b[0] = -100
print(a)

[-100    2    3    4    5    6    7    8    9]


In [92]:
import numpy as np
a=np.arange(1,10,1)
b=a
print(id(a))
print(id(b))
b[0]=-100
print(a)
print(id(a))
print(id(b))


2165764764016
2165764764016
[-100    2    3    4    5    6    7    8    9]
2165764764016
2165764764016


In [93]:
import numpy as np
a=np.arange(1,10,1)
b=a[[1,2,5]]
print(id(a))
print(id(a[1]))
print(id(b))
b[0]=-100


2165764765296
2165763762408
2165764765696


In [95]:
a = np.arange(1, 10, 1)
print(a[a > 5])
print(a > 5)

[6 7 8 9]
[False False False False False  True  True  True  True]


In [98]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [100]:
a = np.array([1, 10 , 100])
print(np.log(a))

[0.         2.30258509 4.60517019]


In [101]:
a=np.array([1,4,9])
print(np.sqrt(a))

[1. 2. 3.]


In [107]:
import numpy as np
a=np.array([1,2,3,4,5])
np.save("D:\\MyDownloads\\a.npy",a)
b=np.load("D:\\MyDownloads\\a.npy")
print(b)

[1 2 3 4 5]


In [1]:
import pandas as pd
data = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/adult/dault.data',
                   header = None, index_col=False,
                   names=['年龄', '单位性质', '权重', '学历', '受教育时长', '婚姻状况', '职业', '家庭情况',
                          '种族', '性别', '资产所得', '资产损失', '周工作时长', '原籍', '收入'])
print(data)

HTTPError: HTTP Error 404: Not Found